#############################
#### REQUIRED PARAMETERS ####
#############################
#Provide an output name for the CanID run
run: name_of_run
#Specify the path to file (space- or tab-delimited) containing list of samples formatted: LIBRARY SAMPLE_ID PATH
files: config/sample_file_list.tsv
#Specify the path to the reference genome (ensure it has a Y-chromosome)
path_to_reference_genome: workflow/files/canis.fa

#Specify the reference panel (depends on target species)
SNP_panel: canis
#Number of chromosomes (autosomes only)
chromosomes: 38
#Labels for sex chromosomes and mitochondria in fasta file 
femaleID: chrX
maleID: chrY
mtDNAID: chrM

#############################
#### OPTIONAL PARAMETERS ####
#############################

#MAPPING
#Enable/disable seed
seed: 1024
#Number of threads
map_threads: 10

#MTDNA CONSENSUS
#Minimum number of bases needed to call mtDNA base
base_depth: 1
#Minimum consensus need to call mtDNA base
base_con: 0.5

#PSEUDOHAPLOID GENOTYPE CALLING
mapping_qual: 30 
base_qual: 30
trimn: 5 
